### ISSUE TITLE
Interested in the project

### ISSUE THREAD

**Issue by tanhauhau** [siong1987/carpool#1]
Hi there, I am a Malaysian too!
I would like to contribute to the project, but not sure how to start with it.
I have great experience in writing React application as a front end engineer, interested to see how I can contribute into the ruby application of yours

**Comment by sssionggg** [comment]
@tanhauhau i decided not to launch this project and am currently working with the #pulangmengundi team.

send me an email at hello@siong.com? i will connect you.

**Comment by tanhauhau** [comment]
@siong1987  sure. my email address lhtan93@gmail.com
just in case it went into the spam folder

**Comment by sssionggg** [comment]
@tanhauhau i got the email. will connect :)
